apiVersion: v1
kind: Service
metadata:
  name: purrfectmatch-frontend-service
spec:
  type: NodePort
  selector:
    app: purrfectmatch-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
