apiVersion: apps/v1
kind: Deployment
metadata:
  name: purrfectmatch-backend
  namespace: purrfectmatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: purrfectmatch-backend
  template:
    metadata:
      labels:
        app: purrfectmatch-backend
    spec:
      containers:
        - name: purrfectmatch-backend
          image: usaidafzal/purrfectmatch-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: purrfectmatch-backend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: purrfectmatch-backend-service
  namespace: purrfectmatch
spec:
  selector:
    app: purrfectmatch-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
