apiVersion: v1
kind: Service
metadata:
  name: purrfectmatch-backend-service
spec:
  type: NodePort
  selector:
    app: purrfectmatch-backend
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30001
